name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest # Set OS to run on
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]

    steps:     # Set Python versions to test
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies # Install code/dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run package as script # Run a script
        run: |
          python -m toy 1 2

      - name: Run tests # A script to run (in this case pytest)
        run: |
          python -m pytest -vv